version: "3"

services:
    halo:
        image: ${IMAGE_NAME}:latest
        restart: on-failure:3
        depends_on:
            halodb:
                condition: service_healthy
        networks:
            halo_network:
        volumes:
            - ./halo2-${ENV}:/root/.halo2
        ports:
            - "${ACCESS_PORT}:8090"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s
        environment:
            # JVM 参数，默认为 -Xmx256m -Xms256m，可以根据实际情况做调整，置空表示不添加 JVM 参数
            - JVM_OPTS=-Xmx256m -Xms256m
        command:
            - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
            - --spring.r2dbc.username=${ POSTGRES_USER }
            # PostgreSQL 的密码，请保证与下方 POSTGRES_PASSWORD 的变量值一致。
            - --spring.r2dbc.password=${ POSTGRES_PASSWORD }
            - --spring.sql.init.platform=postgresql
            # 外部访问地址，请根据实际需要修改
            - --halo.external-url=http://localhost:8090/
    halodb:
        image: postgres:15.4
        restart: on-failure:3
        networks:
            halo_network:
        volumes:
            - ./db-${ENV}:/var/lib/postgresql/data
        ports:
          - "${DB_ACCESS_PORT}:5432"
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_PASSWORD=${ POSTGRES_PASSWORD }
            - POSTGRES_USER=${ POSTGRES_USER }
            - POSTGRES_DB=halo
            - PGUSER=${ POSTGRES_USER }

networks:
    halo_network: