name: ChammmsBlog Workflow

on:
  pull_request:
    branches:
      - main
      - dev-deploy
      - release-*
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - main
      - dev-deploy
      - release-*
    paths:
      - "**"
      - "!**.md"
  release:
    types:
      - published

concurrency: 
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com/manchaof/

jobs:
  test:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env
      - name: Check Halo
        run: ./gradlew check
      - name: Upload coverage reports to Codecov
        if: github.repository == 'lllzzzcccc/ChammmsBlog'
        uses: codecov/codecov-action@v4

  build:
    runs-on: ubuntu-latest
    if: always() && (needs.test.result == 'skipped' || needs.test.result == 'success')
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env
      - name: Reset version of Halo
        if: github.event_name == 'release'
        shell: bash
        run: |
          # Set the version with tag name when releasing
          version=${{ github.event.release.tag_name }}
          version=${version#v}
          sed -i "s/version=.*-SNAPSHOT$/version=$version/1" gradle.properties
      - name: Build Halo
        run: ./gradlew clean && ./gradlew downloadPluginPresets && ./gradlew build -x check
      - name: Upload Artifacts
        if: github.repository == 'lllzzzcccc/ChammmsBlog'
        uses: actions/upload-artifact@v4
        with:
          name: halo-artifacts
          path: application/build/libs
          retention-days: 1

  github-release:
    runs-on: ubuntu-latest
    if: always() && needs.build.result == 'success' && github.event_name == 'release'
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: halo-artifacts
          path: application/build/libs
      - name: Upload Artifacts
        if: github.repository == 'lllzzzcccc/ChammmsBlog'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} application/build/libs/*

#  build-and-publish-container-image-with-buildpacks:
#    needs: build
#    if: always() && needs.build.result == 'success' && (github.event_name == 'push' || github.event_name == 'release')
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Setup Environment
#        uses: ./.github/actions/setup-env
#      - name: Reset version of Halo
#        if: github.event_name == 'release'
#        shell: bash
#        run: |
#          # Set the version with tag name when releasing
#          version=${{ github.event.release.tag_name }}
#          version=${version#v}
#          sed -i "s/version=.*-SNAPSHOT$/version=$version/1" gradle.properties
#      - name: Publish To Container Registries
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
#          F2C_USERNAME: ${{ secrets.F2C_REGISTRY_USER }}
#          F2C_TOKEN: ${{ secrets.F2C_REGISTRY_TOKEN }}
#          GHCR_USERNAME: ${{ github.repository_owner }}
#          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run:
#          ./gradlew publishToAllRegistries -Prelease=${{ github.event_name == 'release' && 'true' || 'false' }}

  docker-build-and-push:
    if: always() && needs.build.result == 'success' && (github.event_name == 'push' || github.event_name == 'release')
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ (github.event_name == 'release' || github.ref_name == 'main') && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: halo-artifacts
          path: application/build/libs
      - name: Docker Buildx and Push
        id: build_and_push
        uses: ./.github/actions/docker-buildx-push-ChammmsBlog
        with:
          image-name: ${{ vars.IMAGE_BASE_NAME }}
          ghcr-token: ${{ secrets.GITHUB_TOKEN }}
          dockerhub-user: ${{ secrets.DOCKER_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKER_TOKEN }}
          f2c-registry-user: ${{ secrets.F2C_REGISTRY_USER }}
          f2c-registry-token: ${{ secrets.F2C_REGISTRY_TOKEN }}
          aliyun-registry-user: ${{ secrets.ALIYUN_DOCKER_HUB_USER }}
          aliyun-registry-token: ${{ secrets.ALIYUN_DOCKER_HUB_TOKEN }}
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x

  e2e-test:
    if: always() && needs.build.result == 'success' && (github.event_name == 'pull_request' || github.event_name == 'push')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: halo-artifacts
          path: application/build/libs
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/halo-dev/halo-dev:main
          push: false
          context: .
      - name: E2E Testing
        continue-on-error: true
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod u+x /usr/local/bin/docker-compose
          cd e2e && make all
          
  deploy:
    if: always() && needs.build.result == 'success' && (github.event_name == 'push' || github.event_name == 'release')
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    environment: ${{ (github.event_name == 'release' || github.ref_name == 'main') && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - name: Connect to Aliyun server
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
       # 初始化 knownhosts 在 GitHub Actions 作业中设置 SSH 密钥，以便安全地与远程服务器进行交互
      - name: Setup knownhosts
        run: ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Login to Aliyun Docker Registry
        run: |
          ssh root@${{ secrets.SERVER_HOST }} "sudo echo ${{ secrets.ALIYUN_DOCKER_HUB_TOKEN }} | docker login --username=${{ secrets.ALIYUN_DOCKER_HUB_USER }} --password-stdin registry.cn-hangzhou.aliyuncs.com"
      - name: Trigger server deployment script
        run: |
          ssh root@${{ secrets.SERVER_HOST }} "sudo mkdir -p ~/.github/docker-compose"
          scp -r ./.github/docker-compose/* root@${{ secrets.SERVER_HOST }}:~/.github/docker-compose/
          ssh root@${{ secrets.SERVER_HOST }} "cd ./.github/docker-compose && sudo docker-compose -p ${{ vars.IMAGE_BASE_NAME }} down --rmi all || true"
          ssh root@${{ secrets.SERVER_HOST }} "cd ./.github/docker-compose && \
            sudo -E IMAGE_NAME=registry.cn-hangzhou.aliyuncs.com/manchaof/${{ vars.IMAGE_BASE_NAME }}:latest\
            ENV=${{ vars.ENV_NAME }} \
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            ACCESS_PORT=${{ vars.ACCESS_PORT }} \
            DB_ACCESS_PORT=${{ vars.DB_ACCESS_PORT }} \
            docker-compose -p ${{ vars.IMAGE_BASE_NAME }} up -d"